# Generated by Django 3.1.3 on 2020-12-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='identity',
            field=models.SmallIntegerField(choices=[(0, '代理商'), (1, '技术'), (2, '销售'), (3, '管理'), (4, '其他')], default=4, verbose_name='用户分组'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mobile',
            field=models.IntegerField(blank=True, verbose_name='手机号'),
        ),
    ]
