# Generated by Django 3.1.3 on 2020-12-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201223_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='work_id',
            field=models.SmallIntegerField(blank=True, null=True, unique=True, verbose_name='工号'),
        ),
    ]
