# Generated by Django 3.1.3 on 2020-12-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201223_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nick_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='昵称'),
        ),
    ]
